
name: libretro Core Info Package

on:
  workflow_dispatch:

jobs:
  Assets:
    name: Bundle Core Info Files
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
    - uses: actions/checkout@v2
    - name: fetch
      run: |
       ./libretro-fetch.sh --devkit --lutro --players --retroarch ppsspp 
       cd /opt/devkitpro/cmake
       cmake -S /__w/libretro-super-ctrbuildz/libretro-super-ctrbuildz/libretro-easyrpg/builds/libretro/ -B /__w/libretro-super-ctrbuildz/libretro-super-ctrbuildz/libretro-easyrpg/builds/libretro/3ds -DCMAKE_MAKE_PROGRAM=make -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/3DS.cmake
       cd /__w/libretro-super-ctrbuildz/libretro-super-ctrbuildz/libretro-easyrpg/builds/libretro/3ds
       make -j42069
    - run:  7z a -mx=9 easyrpg.7z dist/*
    - name: Upload core info bundle
      uses: svenstaro/upload-release-action@v2
      with:
        file: easyrpg.7z
        tag: Latest
        asset_name: easyrpg.7z
        overwrite: true
