name: libretro Core Info Package

on:
  # Trigger the workflow on push, but only for the master branch
  push:
    branches:
      - master
  watch: # this is a hack that lets repo owners trigger a build by starring
    types: [started]
    if: github.actor == github.event.repository.owner.login

jobs:
  Assets:
    name: Bundle Core Info Files
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: fetch
      run: |
        ls/opt
    - run:  7z a -mx=9 easyrpg.7z dist/*
    - name: Upload core info bundle
      uses: svenstaro/upload-release-action@v2
      with:
        file: easyrpg.7z
        tag: Latest
        asset_name: easyrpg.7z
        overwrite: true
