
name: libretro Core Info Package

on:
  workflow_dispatch:

jobs:
  Assets:
    name: 3DS attempt
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm:latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
       #git clone --recursive https://github.com/devkitPro/libctru.git
       #cd libctru/libctru
       #make -j42069 install
       #export CTRULIB="/opt/devkitpro/libctru"
       #cd ../../
    - name: ffmpeg 3ds
      run: |
       export emuplat=Mupen64plus
       export sysplat=3DS
       
       ./libretro-fetch.sh --devkit --lutro --players --retroarch "$emuplat" 
       cd /opt/devkitpro/cmake
       cmake -S /__w/libretro-super-ctrbuildz/libretro-super-ctrbuildz/libretro-"$emuplat"/ -B /__w/libretro-super-ctrbuildz/libretro-super-ctrbuildz/libretro-"$emuplat"/"$sysplat" -DCMAKE_MAKE_PROGRAM=make -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/"$sysplat".cmake
       cd /__w/libretro-super-ctrbuildz/libretro-super-ctrbuildz/libretro-"$emuplat"/"$sysplat"
       make -j42069
    - run:  7z a -mx=9 dist.7z dist/*
    - name: Upload ffmpeg 3ds
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist.7z
        tag: Latest
        asset_name: dist.7z
        overwrite: true
